"""Core analytics functions for suppliers."""
from typing import Dict, List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from shared.database.models import Supplier, SupplierAccount

async def get_supplier_category_distribution(db: AsyncSession) -> dict:
    """Calculates the distribution of suppliers across categories."""
    query = select(Supplier.supplier_category, func.count(Supplier.id)).group_by(Supplier.supplier_category)
    result = await db.execute(query)
    return {category: count for category, count in result.all()}

async def get_total_supplier_revenue(db: AsyncSession, supplier_id: str) -> float:
    """Calculates the total revenue generated by a supplier."""
    query = select(func.sum(SupplierAccount.total_spent)).where(SupplierAccount.supplier_id == supplier_id)
    result = await db.execute(query)
    total_revenue = result.scalar_one_or_none()
    return float(total_revenue) if total_revenue else 0.0

async def get_supplier_intelligence_dashboard(db: AsyncSession) -> Dict:
    """Generates a dashboard with supplier intelligence."""
    category_dist = await get_supplier_category_distribution(db)

    total_suppliers_query = select(func.count(Supplier.id))
    total_suppliers_result = await db.execute(total_suppliers_query)
    total_suppliers = total_suppliers_result.scalar() or 0

    return {
        "summary": {"total_suppliers": total_suppliers},
        "category_distribution": category_dist
    }

async def get_supplier_recommendations(db: AsyncSession, category: Optional[str] = None) -> List[Dict]:
    """Gets supplier recommendations based on performance."""
    query = select(Supplier)
    if category:
        query = query.where(Supplier.supplier_category == category)
    query = query.limit(10)

    result = await db.execute(query)
    suppliers = result.scalars().all()

    return [
        {
            "supplier_id": str(s.id), "name": s.name, "category": s.supplier_category,
            "recommendation_reason": "Top performer in category"
        } for s in suppliers
    ]
