"""Complete schema v2.3.4: DDD domains with catalog, inventory, sales, supplier, financial

Revision ID: 391b4113b939
Revises: b12e96585c37
Create Date: 2025-10-22 05:31:02.263298

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '391b4113b939'
down_revision = 'b12e96585c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_accuracy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_run_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('forecast_level', sa.String(length=20), nullable=False),
    sa.Column('forecast_horizon', sa.String(length=20), nullable=False),
    sa.Column('accuracy_date', sa.Date(), nullable=False),
    sa.Column('mape_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rmse_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mae_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('r2_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('bias_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('records_evaluated', sa.Integer(), nullable=False),
    sa.Column('evaluation_period_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('brand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    schema='catalog'
    )
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='catalog'
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='core'
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('error_records', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='integration'
    )
    op.create_table('event_store',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='logging'
    )
    op.create_index(op.f('ix_logging_event_store_aggregate_id'), 'event_store', ['aggregate_id'], unique=False, schema='logging')
    op.create_index(op.f('ix_logging_event_store_causation_id'), 'event_store', ['causation_id'], unique=False, schema='logging')
    op.create_index(op.f('ix_logging_event_store_correlation_id'), 'event_store', ['correlation_id'], unique=False, schema='logging')
    op.create_index(op.f('ix_logging_event_store_event_id'), 'event_store', ['event_id'], unique=True, schema='logging')
    op.create_index(op.f('ix_logging_event_store_event_type'), 'event_store', ['event_type'], unique=False, schema='logging')
    op.create_index(op.f('ix_logging_event_store_timestamp'), 'event_store', ['timestamp'], unique=False, schema='logging')
    op.create_table('stockx_presale_markings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stockx_listing_id', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('is_presale', sa.Boolean(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unmarked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='logging'
    )
    op.create_index(op.f('ix_logging_stockx_presale_markings_stockx_listing_id'), 'stockx_presale_markings', ['stockx_listing_id'], unique=True, schema='logging')
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_table', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='logging'
    )
    op.create_table('marketplace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('supports_fees', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    schema='platform'
    )
    op.create_table('profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('supplier_type', sa.String(length=50), nullable=False),
    sa.Column('business_size', sa.String(length=30), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('business_registration', sa.String(length=100), nullable=True),
    sa.Column('return_policy_days', sa.Integer(), nullable=True),
    sa.Column('return_policy_text', sa.Text(), nullable=True),
    sa.Column('return_conditions', sa.String(length=500), nullable=True),
    sa.Column('accepts_exchanges', sa.Boolean(), nullable=True),
    sa.Column('restocking_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reliability_score', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('preferred', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('average_processing_days', sa.Integer(), nullable=True),
    sa.Column('ships_internationally', sa.Boolean(), nullable=True),
    sa.Column('accepts_returns_by_mail', sa.Boolean(), nullable=True),
    sa.Column('provides_authenticity_guarantee', sa.Boolean(), nullable=True),
    sa.Column('has_api', sa.Boolean(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=200), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('total_orders_count', sa.Integer(), nullable=True),
    sa.Column('total_order_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supplier_category', sa.String(length=50), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('return_policy', sa.Text(), nullable=True),
    sa.Column('default_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='supplier'
    )
    op.create_table('brand_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog.brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern'),
    schema='catalog'
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_resale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog.brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    schema='catalog'
    )
    op.create_table('sizes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('standardized_value', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('supplier_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('month_year', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('avg_delivery_time', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('return_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('import_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['integration.import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='integration'
    )
    op.create_table('brand_multipliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('multiplier_type', sa.String(length=50), nullable=False),
    sa.Column('multiplier_value', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog.brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('price_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('base_markup_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('maximum_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('condition_multipliers', sa.JSON(), nullable=True),
    sa.Column('seasonal_adjustments', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog.brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.category.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.marketplace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('proxy_config', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('address_line_1', sa.String(length=200), nullable=True),
    sa.Column('address_line_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('payment_provider', sa.String(length=50), nullable=True, comment='Payment provider: stripe, paypal, etc'),
    sa.Column('payment_method_token', sa.String(length=255), nullable=True, comment='Tokenized payment method ID'),
    sa.Column('payment_method_last4', sa.String(length=4), nullable=True, comment='Last 4 digits for display only'),
    sa.Column('payment_method_brand', sa.String(length=20), nullable=True, comment='Card brand: visa, mastercard, etc'),
    sa.Column('expiry_month', sa.Integer(), nullable=True, comment='Expiry month for display/validation'),
    sa.Column('expiry_year', sa.Integer(), nullable=True, comment='Expiry year for display/validation'),
    sa.Column('browser_preference', sa.String(length=50), nullable=True),
    sa.Column('list_name', sa.String(length=100), nullable=True),
    sa.Column('account_status', sa.String(length=30), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('total_purchases', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'email', name='uq_supplier_account_email'),
    schema='supplier'
    )
    op.create_table('demand_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('analysis_level', sa.String(length=20), nullable=False),
    sa.Column('pattern_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('demand_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('velocity_rank', sa.Integer(), nullable=True),
    sa.Column('seasonality_factor', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('volatility_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('pattern_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog.brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('pricing_kpis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('aggregation_level', sa.String(length=20), nullable=False),
    sa.Column('average_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_markup_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_realization_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('competitive_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conversion_rate_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('revenue_impact_eur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('units_sold', sa.Integer(), nullable=True),
    sa.Column('average_selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_elasticity', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog.brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.category.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.marketplace.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('sales_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_run_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('forecast_level', sa.String(length=20), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_horizon', sa.String(length=20), nullable=False),
    sa.Column('forecasted_units', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forecasted_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_lower', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_upper', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog.brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.category.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.marketplace.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('source_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Data source: awin, webgains, scraping, etc.'),
    sa.Column('supplier_name', sa.String(length=100), nullable=False, comment='Retailer/supplier name'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='External product ID from source'),
    sa.Column('buy_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete source data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='integration'
    )
    op.create_table('stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gross_purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('profit_per_shelf_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('listed_stockx', sa.Boolean(), nullable=True),
    sa.Column('listed_alias', sa.Boolean(), nullable=True),
    sa.Column('listed_local', sa.Boolean(), nullable=True),
    sa.Column('detailed_status', sa.Enum('incoming', 'available', 'consigned', 'need_shipping', 'packed', 'outgoing', 'sale_completed', 'cancelled', name='inventory_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['core.sizes.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('size_value', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('lowest_ask', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('highest_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_sale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sales_volume', sa.Integer(), nullable=True),
    sa.Column('premium_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('purchase_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('order_reference', sa.String(length=100), nullable=True),
    sa.Column('purchase_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('purchase_status', sa.String(length=30), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['supplier.account.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='supplier'
    )
    op.create_table('marketplace_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_listing_id', sa.String(length=255), nullable=True, comment='External listing identifier'),
    sa.Column('ask_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Current ask price'),
    sa.Column('bid_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Current bid price'),
    sa.Column('market_lowest_ask', sa.Numeric(precision=10, scale=2), nullable=True, comment='Lowest ask on the market'),
    sa.Column('market_highest_bid', sa.Numeric(precision=10, scale=2), nullable=True, comment='Highest bid on the market'),
    sa.Column('last_sale_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Most recent sale price'),
    sa.Column('sales_frequency', sa.Integer(), nullable=True, comment='Number of sales in last 30 days'),
    sa.Column('volatility', sa.Numeric(precision=5, scale=4), nullable=True, comment='Price volatility (0.0-1.0)'),
    sa.Column('fees_percentage', sa.Numeric(precision=5, scale=4), nullable=True, comment='Platform fees (0.08 = 8%)'),
    sa.Column('platform_specific', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform-specific metadata'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fees_percentage >= 0 AND fees_percentage <= 1', name='chk_fees_range'),
    sa.CheckConstraint('volatility >= 0 AND volatility <= 1', name='chk_volatility_range'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.stock.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.marketplace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'platform_id', name='uq_marketplace_data_item_platform'),
    schema='analytics'
    )
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('buyer_destination_country', sa.String(length=100), nullable=True),
    sa.Column('buyer_destination_city', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.stock.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.marketplace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='financial'
    )
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_type', sa.String(length=30), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.stock.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.marketplace.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_table('listing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('stockx_listing_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('inventory_type', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stockx_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stockx_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_specific_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform-specific fields (StockX, eBay, GOAT, Alias)'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_listing_status'), 'listing', ['status'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_listing_stockx_listing_id'), 'listing', ['stockx_listing_id'], unique=True, schema='sales')
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('stockx_order_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('inventory_type', sa.String(length=50), nullable=True),
    sa.Column('shipping_label_url', sa.String(length=512), nullable=True),
    sa.Column('shipping_document_path', sa.String(length=512), nullable=True),
    sa.Column('stockx_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stockx_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gross_sale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_proceeds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payout_received', sa.Boolean(), nullable=True),
    sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('platform_specific_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform-specific fields (StockX, eBay, GOAT, Alias)'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.stock.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['sales.listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_order_payout_received'), 'order', ['payout_received'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_order_sold_at'), 'order', ['sold_at'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_order_status'), 'order', ['status'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_order_stockx_order_number'), 'order', ['stockx_order_number'], unique=True, schema='sales')
    op.create_table('pricing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Previous price'),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='New price'),
    sa.Column('change_reason', sa.String(length=100), nullable=True, comment='Reason for price change'),
    sa.Column('market_lowest_ask', sa.Numeric(precision=10, scale=2), nullable=True, comment='Market lowest ask at time of change'),
    sa.Column('market_highest_bid', sa.Numeric(precision=10, scale=2), nullable=True, comment='Market highest bid at time of change'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['sales.listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_history', schema='sales')
    op.drop_index(op.f('ix_sales_order_stockx_order_number'), table_name='order', schema='sales')
    op.drop_index(op.f('ix_sales_order_status'), table_name='order', schema='sales')
    op.drop_index(op.f('ix_sales_order_sold_at'), table_name='order', schema='sales')
    op.drop_index(op.f('ix_sales_order_payout_received'), table_name='order', schema='sales')
    op.drop_table('order', schema='sales')
    op.drop_index(op.f('ix_sales_listing_stockx_listing_id'), table_name='listing', schema='sales')
    op.drop_index(op.f('ix_sales_listing_status'), table_name='listing', schema='sales')
    op.drop_table('listing', schema='sales')
    op.drop_table('price_history', schema='pricing')
    op.drop_table('transaction', schema='financial')
    op.drop_table('marketplace_data', schema='analytics')
    op.drop_table('purchase_history', schema='supplier')
    op.drop_table('market_prices', schema='pricing')
    op.drop_table('stock', schema='inventory')
    op.drop_table('source_prices', schema='integration')
    op.drop_table('sales_forecasts', schema='analytics')
    op.drop_table('pricing_kpis', schema='analytics')
    op.drop_table('demand_patterns', schema='analytics')
    op.drop_table('account', schema='supplier')
    op.drop_table('price_rules', schema='pricing')
    op.drop_table('brand_multipliers', schema='pricing')
    op.drop_table('import_records', schema='integration')
    op.drop_table('supplier_performance', schema='core')
    op.drop_table('sizes', schema='core')
    op.drop_table('product', schema='catalog')
    op.drop_table('brand_patterns', schema='catalog')
    op.drop_table('profile', schema='supplier')
    op.drop_table('marketplace', schema='platform')
    op.drop_table('system_logs', schema='logging')
    op.drop_index(op.f('ix_logging_stockx_presale_markings_stockx_listing_id'), table_name='stockx_presale_markings', schema='logging')
    op.drop_table('stockx_presale_markings', schema='logging')
    op.drop_index(op.f('ix_logging_event_store_timestamp'), table_name='event_store', schema='logging')
    op.drop_index(op.f('ix_logging_event_store_event_type'), table_name='event_store', schema='logging')
    op.drop_index(op.f('ix_logging_event_store_event_id'), table_name='event_store', schema='logging')
    op.drop_index(op.f('ix_logging_event_store_correlation_id'), table_name='event_store', schema='logging')
    op.drop_index(op.f('ix_logging_event_store_causation_id'), table_name='event_store', schema='logging')
    op.drop_index(op.f('ix_logging_event_store_aggregate_id'), table_name='event_store', schema='logging')
    op.drop_table('event_store', schema='logging')
    op.drop_table('import_batches', schema='integration')
    op.drop_table('system_config', schema='core')
    op.drop_table('category', schema='catalog')
    op.drop_table('brand', schema='catalog')
    op.drop_table('forecast_accuracy', schema='analytics')
    # ### end Alembic commands ###
